### PR TITLE
Vercel Deployment of Main Branch

### PR DESCRIPTION
**Pull request by Sushmita-Ghosh**
The application main branch is deployed on vercel:  https://color-picker-project-omega.vercel.app/

Modified Readme files to add the links and 1 small configuration change.

### CODE REVIEW

**Review by BrianSlaby — APPROVED** [review]
This looks good to me!  In addition to having the main branch deployed, we will also want to have the development branch deployed to Vercel for testing purposes.

Currently, our development branch is ahead of main.

**Review by jonathanwmendez — DISMISSED** [review]
Looks Good! I second Brian that we also need a live link for the development branch as well to test functionality on the website without changing the live version.

**Comment by BrianSlaby** [comment]
I believe deployment of the development branch is done entirely on Vercel, so changes shouldn't be required for this PR.  It should be ok to merge.

**Review by jonathanwmendez — APPROVED** [review]
Looks good to merge!

**Pull request merged**
